language: python

python:
  - "3.7"

# command to install dependencies
install:
  - pip install -r requirements.txt
  
script: make test

deploy: heroku
  provider: heroku
  api_key:
    secure: travis encrypt $(heroku auth:token) --add deploy.api_key 
  app: blooming-taiga-86486
  on:
    repo: alake16/Distributed-Systems